#!/bin/bash
# Copyright (c) 2010 Michael Sotnikov, stari4ek(at)gmail.com
# This file is part of 7kitchen - collection of scripts for 7hero
#
# Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
source 7common


# defaults
KERNEL_DIR=/home/astar/android/src/7hero_kernel
AOSP_DIR=/home/astar/android/aosp
RAMDISK_DIR=/home/astar/android/kitchen/ramdisk
CONF_DIR=`get_binpath`/7conf/`basename $0`
CROSS_COMPILE=arm-linux-androideabi-
MAKE_J=5

usage()
{
cat << EOF
Usage:
	`basename $0` [OPTIONS] <out>

Build all 7hero kernels and wifi module for HTC hero. Pack it to boot.img and update.zip

OPTIONS:
  -h,  --help              Show this message
  -k,  --kernel <path>     Override kernel path (def: $KERNEL_DIR)
  -a,  --aosp <path>       Override AOSP path (def: $AOSP_DIR)
  -p,  --cc-prefix         Cross compiler prefix (def: $CROSS_COMPILE)
                           (def: $CONF_DIR)
  -r,  --ramdisk <path>    Override ramdisk path (def: $RAMDISK_DIR)
       --configs <path>    Specify script config's (use update script from it)
       --no-update         Do not create update package
  -j <N>                   Number of parallel tasks for make (def: $MAKE_J)
  -v,  --verbose           Verbose
EOF
exit 1
}

set -- `getopt -n$0 -u -o "hk:a:p:r:j:v" -l "help kernel: aosp: cc-prefix: ramdisk: configs: no-update verbose" -- $@` || usage

CONFIGS_STR=''
NOUPDATE=0
NOUPDATE_STR=''
VERBOSE=
VERBOSE_STR=''
while [ $# -gt 0 ]; do
	case "$1" in
		-h|--help)		usage;;
		-k|--kernel)	KERNEL_DIR=$2; shift;;
		-a|--aosp)		AOSP_DIR=$2; shift;;
		-p|--cc-prefix) CROSS_COMPILE=$2; shift;;
		--configs)		CONFIGS_STR='--configs $2'; shift;;
		-j)				MAKE_J=$2; shift;;
		-r|--ramdisk)	RAMDISK_DIR=$2; shift;;
		--no-update)	NOUPDATE=1; NOUPDATE_STR='--no-update';;
		-v|--verbose)	VERBOSE=1; VERBOSE_STR='-v';;
		--)				shift; break;;
	esac
	shift
done

test $# -eq 1 || usage
OUT=`readlink -f $1`

mkdir -p $OUT || 7die "failed to create output dir '$OUT'" 1

for CONIG_PATH in `find ~/android/src/7hero_kernel/arch/arm/configs/ -name '7hero_*' | sort`; do
	CONFIG=`basename $CONIG_PATH`
	7buildkernel -k $KERNEL_DIR -a $AOSP_DIR -p $CROSS_COMPILE $CONFIGS_STR -j $MAKE_J -r $RAMDISK_DIR $NOUPDATE_STR $VERBOSE_STR -c $CONFIG $OUT/$CONFIG || 7die "failed" 1
done

7verbose "done."

