#!/bin/bash
source 7common

if [ "$1" = "" ]; then
	echo "Usage:"
	echo "	`basename $0` <out_dir>"
	exit 1
fi

OUT=`readlink -f $1`
mkdir -p $OUT

KERNEL_DIR=/home/astar/android/src/hero_kernel

function build {
	echo "Build $1"

	OLDPWD=`pwd`
	cd $KERNEL_DIR || die "  failed" 1
	make $1 || die ".. failed" 1
	cd $OLDPWD

	7buildkernel $OUT/$1 || die "failed" 1
	mv -f $OUT/$1/boot.img $OUT/$1.img
	mv -f $OUT/$1/kernel-update.zip $OUT/$1.zip
	rm -rf $OUT/$1
}

# backup config
BACK_CONF=$KERNEL_DIR/config-beforebuild
if [ -r $KERNEL_DIR/.config ]; then
	mv -f $KERNEL_DIR/.config $BACK_CONF
fi

build 7hero_defconfig || die "exit" 1
build 7hero_nploc_defconfig || die "exit" 1
build 7hero_ploc652_defconfig || die "exit" 1
build 7hero_ploc691_defconfig || die "exit" 1
build 7hero_ploc710_defconfig || die "exit" 1

if [ -r $BACK_CONF ]; then
	mv -f $BACK_CONF $KERNEL_DIR/.config
fi

echo "done."
