#!/bin/bash
# Copyright (c) 2010 Michael Sotnikov, stari4ek(at)gmail.com
# This file is part of 7kitchen - collection of scripts for 7hero
#
# Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.

# extenstin
function get_ext {
	BASE=`basename $1`
	EXT=${BASE##*.}
	echo $EXT
}


# basename without extension
function get_basename { 
	EXT=`get_ext $1`
	BASENAME=`basename $1 .$EXT`
	echo $BASENAME
}


# executor's path
function get_binpath {
	MYFULLPATH=`readlink -f $0`
	echo `dirname $MYFULLPATH`
}

# absolute dir path
function get_dirpath {
	MYFULLPATH=`readlink -f $1`
	echo `dirname $MYFULLPATH`
}


# replace ext
function replace_ext {
	EXT=`get_ext $1`
	echo $1 | sed s/.$EXT$/$2/
}


# exit with message
function 7die {
	echo $1
	exit $2
}

#
function 7verbose {
	[ "$VERBOSE" != "" ] && [ $VERBOSE -eq 1 ] && echo $1
}

#
function 7clean {
	( [ "$NOCLEAN" == "" ] || [ $NOCLEAN -ne 1 ] ) && rm -rf $1
}

#
function 7pause {
	read -p 'Press Enter to continue…'
}

