#!/bin/bash
# Copyright (c) 2010 Michael Sotnikov, stari4ek(at)gmail.com
# This file is part of 7kitchen - collection of scripts for 7hero
#
# Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
source 7common

usage()
{
cat << EOF
Unpack resources and smali for all apk/jar in the rom.

Usage:
	`basename $0` <rom> <out>

OPTIONS:
  -h,  --help              Show this message
  -v,  --verbose           Verbose
  -f,  --force             Overwrite if already exist
       --no-src            Do not decode sources (smali)
       --no-res            Do not decode resources
       --no-boot           Do not unpack boot
       --htc               HTC resources should be installed
       --ignore-errors     Ignore errors occured while decoding
EOF
exit 1
}

set -- `getopt -n$0 -u -o "hvf" -l "help verbose force no-src no-res no-boot htc ignore-errors" -- $@` || usage

VERBOSE=0
VERBOSE_STR=''
FORCE_STR=''
NO_SRC_STR=''
NO_RES_STR=''
NO_BOOT=0
HTC_COMPATIBLE=0
IGNORE_ERRORS_STR=''
while [ $# -gt 0 ]; do
	case "$1" in
		-h|--help)			usage;;
		-v|--verbose)		VERBOSE=1; VERBOSE_STR='-v';;
		-f|--force)			FORCE_STR='--force';;
		--no-src)			NO_SRC_STR='--no-src';;
		--no-res)			NO_RES_STR='--no-res';;
		--no-boot)			NO_BOOT=1;;
		--htc)				HTC_COMPATIBLE=1;;
		--ignore-errors)	IGNORE_ERRORS_STR='--ignore-errors';;
		--)				shift; break;;
	esac
	shift
done

test $# -eq 2 || usage
IN=$1
test -d $IN || 7die "Can't open src dir '$IN'" 1

OUT=$2
if [ -d $OUT ]; then
	echo "Non-empty out dir '$OUT'. Will be removed"
	7pause
	rm -fr $OUT
fi

mkdir -p $OUT || 7die "failed to create $OUT" 1

if [ $NO_BOOT -eq 0 ]; then
	7verbose "Unpacking boot with ramdisk"
	7unpack-boot $IN/boot.img $OUT/boot || 7die "failed" 1
fi

7verbose "Installing framework"
if [ $VERBOSE -eq 1 ]; then
	apktool $VERBOSE_STR if $IN"/system/framework/framework-res.apk" || 7die "failed" 1
	test $HTC_COMPATIBLE -eq 0 || apktool $VERBOSE_STR if $IN"/system/framework/com.htc.resources.apk" || 7die "failed" 1
else
	apktool $VERBOSE_STR if $IN"/system/framework/framework-res.apk" 2> /dev/null || exit 1
	test $HTC_COMPATIBLE -eq 0 || apktool $VERBOSE_STR if $IN"/system/framework/com.htc.resources.apk" 2> /dev/null || 7die "failed" 1
fi

function do_it_for {
	7decodedir $VERBOSE_STR $FORCE_STR $NO_SRC_STR $NO_RES_STR $IGNORE_ERRORS_STR --rom $IN $IN"$1" $OUT"$1" || 7die "failed" 1
}

do_it_for /system/framework
do_it_for /system/app
do_it_for /data/app

7verbose "Oh yeah, baby! It's done."
