#!/bin/bash

if [ "$1" = "" ] || [ "$2" = "" ] || [ "$3" = "" ]; then
	echo "Usage:"
	echo "	`basename $0` <src> <rom> <out>"
	exit 1
fi

if [ ! -d "$1" ] || [ ! -d "$2" ]; then
	echo "Can't open dir '$1' dir '$2'"
	exit 1
fi

if [ ! -d "$3" ]; then
	mkdir -p $3
fi

echo "Decoding dir `basename $1`"
for FILE in $1/*
do
	BASE=`basename $FILE`
	EXT=${BASE##*.}
	if [ ! "$EXT" = "odex" ]; then
		# check if it exists already
		BASEFILENAME=`basename $BASE .$EXT`
		DECODED=$3/$BASEFILENAME
		if [ ! -e "$DECODED" ]; then
			7decodeapp $FILE $2 $DECODED || exit 1
		fi
	fi 
done
