#!/bin/bash
# Copyright (c) 2010 Michael Sotnikov, stari4ek(at)gmail.com
# This file is part of 7kitchen - collection of scripts for 7hero
#
# Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
source 7common

usage()
{
cat << EOF
Usage:
	`basename $0` [OPTIONS] <src> <rom> <out>

Deodex sepcified package (apk/jar).

OPTIONS:
  -h,  --help              Show this message
  -n,  --no-clean          Do not remove temporary files
  -c,  --configs=path      Specify path to `basename $0` include/exclude configs
  -v,  --verbose           Verbose
EOF
exit 1
}

set -- `getopt -n$0 -u -o "hnc:v" -l "help no-clean configs: verbose" -- $@` || usage

# TODO: compression level
NOCLEAN=0
CONFIGS=
VERBOSE=
VERBOSE_STR=''
while [ $# -gt 0 ]; do
	case "$1" in
		-h|--help)		usage;;
		-n|--no-clean)	NOCLEAN=1;;
		-c|--configs)	CONFIGS=$2; shift;;
		-v|--verbose)	VERBOSE=1; VERBOSE_STR='-v';;
		--)				shift; break;;
	esac
	shift
done

test $# -eq 3 || usage
test -r $1 || 7die "Can't open src '$1'" 1
test -r $2 || 7die "Can't open rom '$2'" 1

if [ `get_ext $1` = "odex" ]; then
	7die "Specify app instead of it's odex as input" 1
fi

BASE=`basename $1`
7verbose "Deodexing $BASE"

ODEX=`replace_ext $1 .odex`
test -r $ODEX || 7die "Can't open odex for '$BASE'" 1

UNODEXED=`dirname $3`/`basename $3`.unodexed

function do_die {
	7clean $UNODEXED
	7die "failed" 1
}

rm -rf $UNODEXED
7unodex $ODEX $2 $UNODEXED || do_die

7verbose "Generating classes.dex"
smali $UNODEXED -o $UNODEXED/classes.dex || do_die

OUT=$UNODEXED/`basename $3`
cp $1 $OUT || do_die

if [ -r $UNODEXED/classes.dex ]; then
	# TODO: make separated script
	OLDPWD=`pwd`
	cd $UNODEXED
	ZIPNAME=`basename $3`

	7verbose "Injecting classes.dex to '$ZIPNAME'"
	zip -mq $ZIPNAME classes.dex || do_die
	cd $OLDPWD
else
	echo "Can't find classes.dex. WTF?"
	7pause
	exit 1
fi

7signalign $OUT $3 || do_die
7clean $UNODEXED

