#!/bin/bash

source 7common

if [ "$1" = "" ] || [ "$2" = "" ] || [ "$3" = "" ]; then
	echo "Usage:"
	echo "	`basename $0` <src_app> <rom> <out_dir>"
	exit 1
fi

if [ ! -r $1 ] || [ ! -d $2 ]; then
	echo "Can't open '$1', dir '$2"
	exit 1
fi

mkdir -p $3

echo "Disassembling '`basename $1`'"

ODEX=`replace_ext $1 ".odex"`
if [ -r $ODEX ]; then
	echo "  .odex found."
	7unodex $ODEX $2 $3 || exit 1
else
	7getdex $1 $2 $3 || exit 1

	DEX=$3"/classes.dex"
	7undex $DEX $2 $3 || exit 1

	7clean $DEX
fi

