#!/bin/bash

source 7common

if [ "$1" = "" ] || [ "$2" = "" ] || [ "$3" = "" ]; then
	echo "Usage:"
	echo "	`basename $0` <src_app> <rom> <out_dir>"
	exit 1
fi

if [ ! -r $1 ] || [ ! -d $2 ]; then
	echo "Can't open '$1', dir '$2'"
	exit 1
fi

BASE=`basename $1`
echo "Decoding resources for '$BASE'"

mkdir -p $3

# decoding resources only, if permitted
EXCLUDECFG=`get_binpath`/7conf/7decode/exclude.conf
if ! echo "$BASE" | grep -E -f $EXCLUDECFG > /dev/null; then
	# if there is classes.dex already - backup it
	DEX=$3/"classes.dex"
	DEXBAK=$DEX".bak"
	if [ -r $DEX ]; then
		mv $DEX $DEXBAK
	fi

	echo "  extracting resources"
	apktool decode -s -f $1 $3
	if [ ! $? ]; then
		echo "    failed"
		exit 1
	fi

	# don't need it here
	rm -f $DEX

	# get previous dex back, if it existed
	if [ -r $DEXBAK ]; then
		mv $DEXBAK $DEX
	fi
	
else
	echo "  ignoring"
fi

