#!/bin/bash

if [ "$1" = "" ] || [ "$2" = "" ] || [ "$3" = "" ]; then
	echo "Usage:"
	echo "	`basename $0` <src> <rom> <out_dir>"
	exit 1
fi

if [ ! -r $1 ] || [ ! -d $2 ]; then
	echo "Can't open '$1', dir '$2'"
	exit 1
fi

mkdir -p $3

BASE=`basename $1`
echo "Extracting .dex from '$BASE'"

EXT=${BASE##*.}
ODEX=`echo $1 | sed s/.$EXT$/.odex/`
# un(o)dex
if [ -r $ODEX ]; then
	echo "  .odex found."
	SMALI=$3"/smali"
	7unodex $ODEX $2 $SMALI || exit 1

	echo "Dexing for '$BASE'"
	smali $SMALI -o $3/classes.dex
	if [ ! $? ]; then
		echo "  failed"
		exit 1
	fi

	7clean $SMALI
else
	unzip -o $1 classes.dex -d $3
	if [ ! $? ]; then
		echo "  failed"
		exit 1
	fi
fi
