#!/bin/bash


if [ "$1" = "" ] || [ "$2" = "" ]; then
	echo "Usage:"
	echo "	`basename $0` <src_app> <out_app>"
	exit 1
fi

if [ ! -r $1 ]; then
	echo "Can't open '$1'"
	exit 1
fi

BASE=`basename $1`
echo "Resigning '$BASE'"

7signalign $1 $2 || exit 1
7copyappodex $1 $2 || exit 1

