#!/bin/bash

if [ "$1" = "" ] || [ "$2" = "" ] || [ "$3" = "" ]; then
	echo "Usage:"
	echo "	`basename $0` <src> <rom> <out>"
	exit 1
fi

if [ ! -r $1 ] || [ ! -d $2 ]; then
	echo "Can't open '$1', dir '$2'"
	exit 1
fi

BASE=`basename $1`
EXT=${BASE##*.}
if [ ! "$EXT" = "dex" ]; then
	echo "Source '$1' isn't dex"
	exit 1
fi

MYPATH=`readlink -f $0`
MYDIR=`dirname $MYPATH`
DEPPATH=$MYDIR/7conf/7unodex

echo "Undexing $BASE"
#DEBUGFLG=
DEBUGFLG=--no-debug-info
baksmali $DEBUGFLG -d $2/system/framework -o $3 $1
if [ ! $? ]; then
	7clean $3
	echo "..failed"
	exit 1
fi

