#!/bin/bash

if [ "$1" = "" ] || [ "$2" = "" ]; then
	echo "Usage:"
	echo "	`basename $0` <src> <out>"
	exit 1
fi

if [ ! -r $1 ]; then
	echo "Can't open '$1'"
	exit 1
fi

echo "Unpacking `basename $1`"

if [ ! -d $2 ]; then
	mkdir -p $2
fi

unzip -o -q -d $2 $1
if [ ! $? ]; then
	echo "  failed"
	7clean $2
	exit 1
fi

# remove old certificate
rm -rf $2/META-INF/CERT.RSA
rm -rf $2/META-INF/CERT.SF
rm -rf $2/META-INF/MANIFEST.MF
